// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocialNetwork.Models;

#nullable disable

namespace SocialNetwork.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20251211022930_db")]
    partial class db
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SocialNetwork.Models.Category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("deleted")
                        .HasColumnType("bit");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("user_id");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("SocialNetwork.Models.Comment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("deleted")
                        .HasColumnType("bit");

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("post_id")
                        .HasColumnType("int");

                    b.Property<string>("publicId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("post_id");

                    b.HasIndex("user_id");

                    b.ToTable("comments");
                });

            modelBuilder.Entity("SocialNetwork.Models.CommentRep", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int?>("comentRep2")
                        .HasColumnType("int");

                    b.Property<string>("comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("commentRep3")
                        .HasColumnType("int");

                    b.Property<int?>("comment_Id")
                        .HasColumnType("int");

                    b.Property<string>("creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("deleted")
                        .HasColumnType("bit");

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("publicId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("comentRep2");

                    b.HasIndex("comment_Id");

                    b.HasIndex("user_id");

                    b.ToTable("commentReps");
                });

            modelBuilder.Entity("SocialNetwork.Models.image_user", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("deleted")
                        .HasColumnType("bit");

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("public_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("user_id");

                    b.ToTable("image_Users");
                });

            modelBuilder.Entity("SocialNetwork.Models.Like", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("deleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("isLiked")
                        .HasColumnType("bit");

                    b.Property<int?>("post_id")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("post_id");

                    b.HasIndex("user_id");

                    b.ToTable("likes");
                });

            modelBuilder.Entity("SocialNetwork.Models.Post", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int?>("category_id")
                        .HasColumnType("int");

                    b.Property<string>("creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("deleted")
                        .HasColumnType("bit");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("isAdminHide")
                        .HasColumnType("bit");

                    b.Property<bool?>("isBackground")
                        .HasColumnType("bit");

                    b.Property<bool?>("isHide")
                        .HasColumnType("bit");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("totalComment")
                        .HasColumnType("int");

                    b.Property<int>("totalLine")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("category_id");

                    b.HasIndex("user_id");

                    b.ToTable("posts");
                });

            modelBuilder.Entity("SocialNetwork.Models.Post_Image", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("deleted")
                        .HasColumnType("bit");

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("post_id")
                        .HasColumnType("int");

                    b.Property<string>("public_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("post_id");

                    b.HasIndex("user_id");

                    b.ToTable("Post_Images");
                });

            modelBuilder.Entity("SocialNetwork.Models.role", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("deleted")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("id");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("SocialNetwork.Models.Tick", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("deleted")
                        .HasColumnType("bit");

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("public_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("id");

                    b.ToTable("ticks");
                });

            modelBuilder.Entity("SocialNetwork.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("cretoredat")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("deleted")
                        .HasColumnType("bit");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fullname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("publicid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("role_id")
                        .HasColumnType("int");

                    b.Property<int?>("tick_id")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("updateat")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("role_id");

                    b.HasIndex("tick_id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("SocialNetwork.Models.Category", b =>
                {
                    b.HasOne("SocialNetwork.Models.User", "user")
                        .WithMany("categories")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("user");
                });

            modelBuilder.Entity("SocialNetwork.Models.Comment", b =>
                {
                    b.HasOne("SocialNetwork.Models.Post", "post")
                        .WithMany("comments")
                        .HasForeignKey("post_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SocialNetwork.Models.User", "user")
                        .WithMany("comments")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("post");

                    b.Navigation("user");
                });

            modelBuilder.Entity("SocialNetwork.Models.CommentRep", b =>
                {
                    b.HasOne("SocialNetwork.Models.CommentRep", "commentRep")
                        .WithMany("commentReps")
                        .HasForeignKey("comentRep2")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SocialNetwork.Models.Comment", "comments")
                        .WithMany("commentReps")
                        .HasForeignKey("comment_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SocialNetwork.Models.User", "user")
                        .WithMany("commentReps")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("commentRep");

                    b.Navigation("comments");

                    b.Navigation("user");
                });

            modelBuilder.Entity("SocialNetwork.Models.image_user", b =>
                {
                    b.HasOne("SocialNetwork.Models.User", "user")
                        .WithMany("image_Users")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("user");
                });

            modelBuilder.Entity("SocialNetwork.Models.Like", b =>
                {
                    b.HasOne("SocialNetwork.Models.Post", "post")
                        .WithMany("likes")
                        .HasForeignKey("post_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SocialNetwork.Models.User", "user")
                        .WithMany("likes")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("post");

                    b.Navigation("user");
                });

            modelBuilder.Entity("SocialNetwork.Models.Post", b =>
                {
                    b.HasOne("SocialNetwork.Models.Category", "category")
                        .WithMany("posts")
                        .HasForeignKey("category_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SocialNetwork.Models.User", "user")
                        .WithMany("posts")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("category");

                    b.Navigation("user");
                });

            modelBuilder.Entity("SocialNetwork.Models.Post_Image", b =>
                {
                    b.HasOne("SocialNetwork.Models.Post", "post")
                        .WithMany("post_Images")
                        .HasForeignKey("post_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SocialNetwork.Models.User", "user")
                        .WithMany("post_Images")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("post");

                    b.Navigation("user");
                });

            modelBuilder.Entity("SocialNetwork.Models.User", b =>
                {
                    b.HasOne("SocialNetwork.Models.role", "roles")
                        .WithMany("users")
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SocialNetwork.Models.Tick", "tick")
                        .WithMany("users")
                        .HasForeignKey("tick_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("roles");

                    b.Navigation("tick");
                });

            modelBuilder.Entity("SocialNetwork.Models.Category", b =>
                {
                    b.Navigation("posts");
                });

            modelBuilder.Entity("SocialNetwork.Models.Comment", b =>
                {
                    b.Navigation("commentReps");
                });

            modelBuilder.Entity("SocialNetwork.Models.CommentRep", b =>
                {
                    b.Navigation("commentReps");
                });

            modelBuilder.Entity("SocialNetwork.Models.Post", b =>
                {
                    b.Navigation("comments");

                    b.Navigation("likes");

                    b.Navigation("post_Images");
                });

            modelBuilder.Entity("SocialNetwork.Models.role", b =>
                {
                    b.Navigation("users");
                });

            modelBuilder.Entity("SocialNetwork.Models.Tick", b =>
                {
                    b.Navigation("users");
                });

            modelBuilder.Entity("SocialNetwork.Models.User", b =>
                {
                    b.Navigation("categories");

                    b.Navigation("commentReps");

                    b.Navigation("comments");

                    b.Navigation("image_Users");

                    b.Navigation("likes");

                    b.Navigation("post_Images");

                    b.Navigation("posts");
                });
#pragma warning restore 612, 618
        }
    }
}
